pipeline {
    agent {
         node {
            label 'Node1'
            //customWorkspace '/some/other/path'
            }
        }
 
    stages {
        stage('Master Branch Deploy Code') {
            
            steps {
                sh """
                echo "Building Artifact from Master branch"
                """

                sh """
                echo "Deploying Code from Master branch"
                """
            }
        }
      stage('Develop Branch Deploy Code') {
          
            steps {
                
                sh "ls -ltr"
                sh "cat update1"
                sh """
                echo "Building Artifact from Develop branch"
                """
                sh """
                echo "Deploying Code from Develop branch"
                """
           }
        }
    }
}

  //test  
  

               